version: '3'
services:
  postgres:
    container_name: first-db
    image: "postgres:15"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hottlbuc
      POSTGRES_USER: hottlbuc
      POSTGRES_PASSWORD: bcbaXAN-75xeMnp3IE3AypAFoCtgliaJ
  web:
    container_name: simple-app
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://surus.db.elephantsql.com:5432/hottlbuc
      SPRING_DATASOURCE_USERNAME: hottlbuc
      SPRING_DATASOURCE_PASSWORD: bcbaXAN-75xeMnp3IE3AypAFoCtgliaJ